apiVersion: 1

datasources:
  - name: Prometheus-Microservices
    type: prometheus
    uid: prometheus-microservices
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"
      httpMethod: "POST"